// generic search page template

import { Table } from "baseui/table-semantic"
import * as React from "react"
import SearchForm from "../components/search-form"

export default ({ render, columns }, query) => ({
    scaffoldServerSideProps: // generate a full getServerSideProps function based on a supplied partial function
        (getServerSideProps = () => ({ props: {} })) =>
            async context => {
                const data = await getServerSideProps(context)
                const search = context.query.busqueda || ""

                const dataSearchProps = {
                    matches: await query(search),
                    search
                }

                if (data && data.props) {
                    const { props, ...rest } = data
                    return {
                        ...rest,
                        props: { ...props, dataSearch: dataSearchProps } // append dataSearch props to props generated by getServerSideProps
                    }
                } else return { props: dataSearchProps }
            },
    DataSearch: ({ state: { matches, search } }) => (
        <section>
            <SearchForm value={search} />
            <Table columns={columns} data={render(matches)} />
        </section>
    )
})
